@Variant1_HostAddress = http://localhost:5126

POST {{Variant1_HostAddress}}/login/
Content-Type: application/json

{
  "login": "ivanko",
  "password": "Qwerty123!"
}

###

POST {{Variant1_HostAddress}}/plants/1/display/1

###

GET {{Variant1_HostAddress}}/displays/1

###

GET {{Variant1_HostAddress}}/plants